export default {
  Account: { id: 'Account', name: 'Account' },
  Auth: { id: 'Auth', name: 'Auth' },
  ChangePassword: { id: 'ChangePassword', name: 'ChangePassword' },
  ForgotPassword: { id: 'ForgotPassword', name: 'ForgotPassword' },
  Home: { id: 'Home', name: 'Home' },
  Login: { id: 'Login', name: 'Login' },
  Main: { id: 'Main', name: 'Main' },
  Membership: { id: 'Membership', name: 'Membership' },
  MyPoint: { id: 'MyPoint', name: 'MyPoint' },
  News: { id: 'News', name: 'News' },
  Notification: { id: 'Notification', name: 'Notification' },
  OTP: { id: 'OTP', name: 'OTP' },
  Products: { id: 'Products', name: 'Products' },
  Recommendations: { id: 'Recommendations', name: 'Recommendations' },
  Register: { id: 'Register', name: 'Register' },
  SignUp: { id: 'SignUp', name: 'SignUp' },
  Splash: { id: 'Splash', name: 'Splash' },
  Stores: { id: 'Stores', name: 'Stores' },
  VoucherCoupon: { id: 'VoucherCoupon', name: 'VoucherCoupon' },
  Welcome: { id: 'Welcome', name: 'Welcome' },
}
